default_context:
  chart_name: "uc2-wp"
  chart_namespace: "uc2"
  chart_version: "0.2.6"
  need_dep_chart: "no"
  include_service: "yes"
  service_name: "windprediction"
  service_image_repo: "registry.apps.eo4eu.eu/eo4eu/eo4eu-inference-server/uc2/eo4eu-windprediction"
  service_image_tag: "9e09834619c6c71f750489c0d8c4832e42a7615d"
  service_image_pull_policy: "Always"
  service_image_secret: "uc2-registry"
  service_container_port: "8080"
  service_request_cpu: "100m"
  service_request_memory: "4G"
  service_limit_cpu: "1"
  service_limit_memory: "16G"
  service_environment_label: "production"
  service_service_label: "UC2"
  service_component_label: "windprediction"
  include_inference_service: "no"
  include_sklearn_inference_service: "no"
  include_sklearn_inference_service2: "no"
  include_namespace: "no"
  include_role: "no"
  include_role_binding: "no"
  include_service_account: "no"
  include_virtual_service: "no"
  include_sklearn_virtual_service: "no"
  include_sklearn_virtual_service2: "no"
  include_external_s3_secret: "no"
  include_external_registry_secret: "no"
  virtual_service_cluster_domain: "cineca-inference-server"